# Generated by Django 5.0.14 on 2026-09-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingslot',
            name='price_per_hour',
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('CARD', 'Credit / Debit Card'), ('CASH', 'Cash at Counter')], default='UPI', max_length=15),
        ),
    ]
